import { Head, Link, useForm } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

interface User {
    name: string;
}

interface Report {
    id: number;
    title: string;
    type: string;
    user: User;
    generated_at: string;
}

interface Props {
    reports: {
        data: Report[];
        links: any;
        meta: any;
    };
}

export default function ReportIndex({ reports }: Props) {
    const {
        post: generateStudentsReport,
        processing: isGeneratingStudentsReport,
    } = useForm({
        title: `Students Report - ${new Date().toLocaleDateString()}`,
        filters: {},
    });
    const { post: generateQueuesReport, processing: isGeneratingQueuesReport } =
        useForm({
            title: `Queues Report - ${new Date().toLocaleDateString()}`,
        });

    const getTypeColor = (type: string) => {
        switch (type) {
            case 'students':
                return 'bg-blue-100 text-blue-800';
            case 'queues':
                return 'bg-purple-100 text-purple-800';
            case 'activity':
                return 'bg-green-100 text-green-800';
            case 'custom':
                return 'bg-gray-100 text-gray-800';
            default:
                return 'bg-gray-100 text-gray-800';
        }
    };

    return (
        <>
            <Head title="Reports" />

            <div className="space-y-6">
                <div className="flex items-center justify-between">
                    <h1 className="text-3xl font-bold">Reports</h1>
                    <div className="flex gap-3">
                        <Button
                            type="button"
                            disabled={isGeneratingStudentsReport}
                            onClick={() =>
                                generateStudentsReport(
                                    route('reports.generate-students'),
                                )
                            }
                        >
                            {isGeneratingStudentsReport
                                ? 'Generating...'
                                : 'Generate Students Report'}
                        </Button>
                        <Button
                            type="button"
                            disabled={isGeneratingQueuesReport}
                            onClick={() =>
                                generateQueuesReport(
                                    route('reports.generate-queues'),
                                )
                            }
                        >
                            {isGeneratingQueuesReport
                                ? 'Generating...'
                                : 'Generate Queues Report'}
                        </Button>
                    </div>
                </div>

                <Card className="p-6">
                    <div className="space-y-4">
                        {reports.data.length > 0 ? (
                            reports.data.map((report) => (
                                <div
                                    key={report.id}
                                    className="rounded-lg border border-gray-200 p-4 transition hover:shadow-md"
                                >
                                    <div className="flex items-start justify-between">
                                        <div className="flex-1">
                                            <h3 className="text-lg font-semibold">
                                                {report.title}
                                            </h3>
                                            <div className="mt-2 text-sm text-gray-600">
                                                <p>
                                                    Generated by:{' '}
                                                    {report.user.name}
                                                </p>
                                                <p>
                                                    Generated at:{' '}
                                                    {new Date(
                                                        report.generated_at,
                                                    ).toLocaleString()}
                                                </p>
                                            </div>
                                        </div>
                                        <div className="flex flex-col items-end gap-2">
                                            <span
                                                className={`inline-block rounded px-3 py-1 text-xs font-semibold ${getTypeColor(
                                                    report.type,
                                                )}`}
                                            >
                                                {report.type
                                                    .charAt(0)
                                                    .toUpperCase() +
                                                    report.type.slice(1)}
                                            </span>
                                            <Link
                                                href={route(
                                                    'reports.show',
                                                    report.id,
                                                )}
                                            >
                                                <Button
                                                    variant="outline"
                                                    size="sm"
                                                >
                                                    View Report
                                                </Button>
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                            ))
                        ) : (
                            <p className="py-8 text-center text-gray-600">
                                No reports generated yet
                            </p>
                        )}
                    </div>
                </Card>
            </div>
        </>
    );
}
