import { Head, Link } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

interface User {
    name: string;
}

interface Report {
    id: number;
    title: string;
    type: string;
    user: User;
    generated_at: string;
}

interface Props {
    reports: {
        data: Report[];
        links: any;
        meta: any;
    };
}

export default function ReportIndex({ reports }: Props) {
    const getTypeColor = (type: string) => {
        switch (type) {
            case 'students':
                return 'bg-blue-100 text-blue-800';
            case 'queues':
                return 'bg-purple-100 text-purple-800';
            case 'activity':
                return 'bg-green-100 text-green-800';
            case 'custom':
                return 'bg-gray-100 text-gray-800';
            default:
                return 'bg-gray-100 text-gray-800';
        }
    };

    return (
        <>
            <Head title="Reports" />

            <div className="space-y-6">
                <div className="flex items-center justify-between">
                    <h1 className="text-3xl font-bold">Reports</h1>
                    <div className="flex gap-3">
                        <Link href={route('reports.generate-students')}>
                            <Button>Generate Students Report</Button>
                        </Link>
                        <Link href={route('reports.generate-queues')}>
                            <Button>Generate Queues Report</Button>
                        </Link>
                    </div>
                </div>

                <Card className="p-6">
                    <div className="space-y-4">
                        {reports.data.length > 0 ? (
                            reports.data.map((report) => (
                                <div key={report.id} className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition">
                                    <div className="flex items-start justify-between">
                                        <div className="flex-1">
                                            <h3 className="text-lg font-semibold">{report.title}</h3>
                                            <div className="mt-2 text-sm text-gray-600">
                                                <p>Generated by: {report.user.name}</p>
                                                <p>Generated at: {new Date(report.generated_at).toLocaleString()}</p>
                                            </div>
                                        </div>
                                        <div className="flex flex-col gap-2 items-end">
                                            <span
                                                className={`inline-block px-3 py-1 text-xs rounded font-semibold ${getTypeColor(
                                                    report.type
                                                )}`}
                                            >
                                                {report.type.charAt(0).toUpperCase() + report.type.slice(1)}
                                            </span>
                                            <Link href={route('reports.show', report.id)}>
                                                <Button variant="outline" size="sm">
                                                    View Report
                                                </Button>
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                            ))
                        ) : (
                            <p className="text-gray-600 text-center py-8">No reports generated yet</p>
                        )}
                    </div>
                </Card>
            </div>
        </>
    );
}
