import { Head, Link, useForm } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

interface User {
    name: string;
}

interface Report {
    id: number;
    title: string;
    type: string;
    description: string | null;
    user: User;
    generated_at: string;
    data: any[];
}

interface Props {
    report: Report;
}

export default function ReportShow({ report }: Props) {
    const { delete: destroy } = useForm();

    const handleDelete = () => {
        if (confirm('Are you sure you want to delete this report?')) {
            destroy(route('reports.destroy', report.id));
        }
    };

    const downloadCSV = () => {
        const csv = convertToCSV(report.data);
        const element = document.createElement('a');
        element.setAttribute('href', 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv));
        element.setAttribute('download', `${report.title}.csv`);
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    };

    const convertToCSV = (data: any[]) => {
        if (!data || data.length === 0) return '';

        const headers = Object.keys(data[0]);
        const csv = [headers.join(','), ...data.map((row) => headers.map((h) => JSON.stringify(row[h])).join(','))];

        return csv.join('\n');
    };

    return (
        <>
            <Head title={report.title} />

            <div className="space-y-6">
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-3xl font-bold">{report.title}</h1>
                        <p className="text-gray-600 mt-2">Type: {report.type}</p>
                    </div>
                    <div className="flex gap-3">
                        <Button onClick={downloadCSV}>Download CSV</Button>
                        <Button variant="destructive" onClick={handleDelete}>
                            Delete Report
                        </Button>
                    </div>
                </div>

                <Card className="p-6 bg-gray-50">
                    <div className="grid grid-cols-2 gap-6">
                        <div>
                            <h3 className="font-semibold text-gray-600">Generated by</h3>
                            <p className="text-lg">{report.user.name}</p>
                        </div>
                        <div>
                            <h3 className="font-semibold text-gray-600">Generated at</h3>
                            <p className="text-lg">{new Date(report.generated_at).toLocaleString()}</p>
                        </div>
                    </div>
                </Card>

                <Card className="p-6">
                    <h2 className="text-lg font-semibold mb-4\">Report Data ({report.data.length} records)</h2>
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="border-b bg-gray-50">
                                    {report.data.length > 0 &&
                                        Object.keys(report.data[0]).map((header) => (
                                            <th key={header} className="px-4 py-2 text-left font-semibold">
                                                {header}
                                            </th>
                                        ))}
                                </tr>
                            </thead>
                            <tbody>
                                {report.data.map((row, index) => (
                                    <tr key={index} className="border-b hover:bg-gray-50">
                                        {Object.values(row).map((value: any, idx) => (
                                            <td key={idx} className="px-4 py-2">
                                                {typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value)}
                                            </td>
                                        ))}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </Card>

                <Link href={route('reports.index')}>
                    <Button variant="outline">Back to Reports</Button>
                </Link>
            </div>
        </>
    );
}
